# Generated by Django 4.2.30 on 2026-06-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_inventory_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
