# Generated by Django 4.2.30 on 2026-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='حداقل مقدار سفارش'),
        ),
    ]
