# Generated by Django 4.2.30 on 2026-09-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_min_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('گرم', 'گرم'), ('کیلو', 'کیلوگرم'), ('عدد', 'عدد'), ('بسته', 'بسته'), ('نخ', 'نخ'), ('پاکت', 'پاکت')], default='کیلو', max_length=20, verbose_name='واحد فروش'),
        ),
    ]
