# Generated by Django 4.2.30 on 2026-08-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان شعبه')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن تماس')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='شماره واتساپ')),
                ('working_hours', models.CharField(blank=True, max_length=150, verbose_name='روزها و ساعات کاری')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('neshan_link', models.URLField(blank=True, verbose_name='لینک مسیریابی در نشان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبه\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
    ]
