# Generated by Django 4.2.30 on 2026-08-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='داستان عطاری آویشن', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
                ('brand_name', models.CharField(default='عطاری آویشن', max_length=150)),
                ('brand_description', models.CharField(blank=True, max_length=250)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('story_title', models.CharField(default='داستان ما و تعهد به سلامت شما', max_length=250)),
                ('story_text_1', models.TextField(blank=True)),
                ('story_text_2', models.TextField(blank=True)),
                ('products_title', models.CharField(default='تنوع محصولات در عطاری آنلاین آویشن', max_length=250)),
                ('products_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'صفحه درباره ما',
                'verbose_name_plural': 'صفحه درباره ما',
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='contact.aboutpage')),
            ],
            options={
                'verbose_name': 'ویژگی صفحه درباره ما',
                'verbose_name_plural': 'ویژگی\u200cهای صفحه درباره ما',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='contact.aboutpage')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی صفحه درباره ما',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای صفحه درباره ما',
                'ordering': ['order', 'id'],
            },
        ),
    ]
